# mypy: ignore-errors
# ruff: noqa
"""hdbResalePriceV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OM7o9phOgpKMDSrsPFzr7njG1AMwz7k
"""

import pandas as pd

# Load the CSV files
file_1990_1999 = "Resale Flat Prices (Based on Approval Date), 1990 - 1999.csv"
file_2000_2012 = "Resale Flat Prices (Based on Approval Date), 2000 - Feb 2012.csv"
file_2015_2016 = "Resale Flat Prices (Based on Registration Date), From Jan 2015 to Dec 2016.csv"
file_2012_2014 = "Resale Flat Prices (Based on Registration Date), From Mar 2012 to Dec 2014.csv"
file_2017_onwards = "Resale flat prices based on registration date from Jan-2017 onwards.csv"

# Read CSV files into DataFrames
df_1990_1999 = pd.read_csv(file_1990_1999)
df_2000_2012 = pd.read_csv(file_2000_2012)
df_2015_2016 = pd.read_csv(file_2015_2016)
del df_2015_2016["remaining_lease"]  # delete column 'remaining_lease'
df_2012_2014 = pd.read_csv(file_2012_2014)
df_2017_onwards = pd.read_csv(file_2017_onwards)
del df_2017_onwards["remaining_lease"]  # delete column 'remaining_lease'

# Merge all the dataframes into a single dataframe
merged_df = pd.concat(
    [df_1990_1999, df_2000_2012, df_2012_2014, df_2015_2016, df_2017_onwards], ignore_index=True
)

# Show a sample of the merged dataframe
merged_df.head()

from google.colab import drive

drive.mount("/content/drive")

# Feature Engineering

# Combine 'flat_type' and 'flat_model' into a new column 'flat_info'
merged_df["flat_info"] = merged_df["flat_type"] + " " + merged_df["flat_model"]

# Combine 'block' and 'street_name' into a new column 'block_street_name'
merged_df["block_street_name"] = merged_df["block"] + " " + merged_df["street_name"]

# Display the first few rows to see the result
print(merged_df[["flat_type", "flat_model", "flat_info", "block_street_name"]].head())

merged_df.head()

# Remove the fields that we don't want to include in our model
del merged_df["block"]
del merged_df["street_name"]
del merged_df["flat_type"]
del merged_df["flat_model"]

merged_df.head()

merged_df.tail()

# Apply categorical data with one-hot encoding
features_df = pd.get_dummies(merged_df, columns=["town", "storey_range", "flat_info"])

features_df.shape

# Convert 'month' to datetime format if not already done
features_df["month"] = pd.to_datetime(merged_df["month"], format="%Y-%m")

# Extract year and month separately
features_df["year"] = features_df["month"].dt.year
features_df["month_num"] = features_df["month"].dt.month

# Convert 'year' and 'month_num' into a float time series
# The month is divided by 12 to convert it into a fraction of a year
features_df["float_time_series"] = features_df["year"] + (features_df["month_num"] - 1) / 12

# Show the first few rows
print(features_df[["month", "float_time_series"]].head())

features_df.head()
features_df.tail()

del features_df["month"]
del features_df["year"]
del features_df["month_num"]

features_df.tail()

# Remove the resale_price from the feature data
del features_df["resale_price"]

# Remove block_street_name from the feature data
del features_df["block_street_name"]

# Create the X and y arrays
X = features_df.to_numpy()
y = merged_df["resale_price"].to_numpy()

import joblib
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

# Split the dataset into training set (70%) and test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

# Create and fit the model
model = ensemble.GradientBoostingRegressor(
    n_estimators=1000,  # how many decision trees to build
    learning_rate=0.1,  # how much decision trees influence overall prediction
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss="huber",
    random_state=7,
)
model.fit(X_train, y_train)

# Save the training model
joblib.dump(model, "models/GBR_trained_hdb_resale_model.pkl")

# Find the error rate on the test dataset
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: ", mae)

# Find the R2 on the test dataset
r2 = r2_score(y_test, model.predict(X_test))
print("R-squared Score: ", r2)

import joblib
from sklearn.metrics import r2_score
from xgboost import XGBRegressor

# Create and fit the model
model = ensemble.RandomForestRegressor(
    n_estimators=1000, max_depth=6, min_samples_leaf=9, max_features=0.1, random_state=7
)
model.fit(X_train, y_train)

# Save the training model
joblib.dump(model, "models/RFR_trained_hdb_resale_model.pkl")

# Find the error rate on the test dataset
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: ", mae)

# Find the R2 on the test dataset
r2 = r2_score(y_test, model.predict(X_test))
print("R-squared Score: ", r2)

import joblib
from sklearn.metrics import r2_score

# Create and fit the model
model = XGBRegressor(
    n_estimators=1000, learning_rate=0.1, max_depth=6, min_child_weight=9, random_state=7
)
model.fit(X_train, y_train)

# Save the training model
joblib.dump(model, "models/XBR_trained_hdb_resale_model.pkl")

# Find the error rate on the test dataset
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: ", mae)

# Find the R2 on the test dataset
r2 = r2_score(y_test, model.predict(X_test))
print("R-squared Score: ", r2)

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

# Define parameter grid

param_grid = {"n_estimators": [800, 1000, 1200]}

# Create XGBoost model
xgb = XGBRegressor(random_state=7)

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=4,
    verbose=100,
)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", -grid_search.best_score_)

# Best model
best_model = grid_search.best_estimator_

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

# Define parameter grid

param_grid = {"learning_rate": [0.01, 0.1, 0.3]}

# Create XGBoost model
xgb = XGBRegressor(random_state=7)

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=4,
    verbose=100,
)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", -grid_search.best_score_)

# Best model
best_model = grid_search.best_estimator_

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

# Define parameter grid

param_grid = {"max_depth": [4, 6, 8]}

# Create XGBoost model
xgb = XGBRegressor(random_state=7)

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=4,
    verbose=100,
)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", -grid_search.best_score_)

# Best model
best_model = grid_search.best_estimator_
print("Best Model: ", best_model)

import joblib
from sklearn.metrics import r2_score
from xgboost import XGBRegressor

# Create and fit the model
model = XGBRegressor(
    n_estimators=1200, learning_rate=0.3, max_depth=8, min_child_weight=9, random_state=7
)
model.fit(X_train, y_train)

# Save the training model
joblib.dump(model, "models/XBR_trained_hdb_resale_model.pkl")

# Find the error rate on the test dataset
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: ", mae)

# Find the R2 on the test dataset
r2 = r2_score(y_test, model.predict(X_test))
print("R-squared Score: ", r2)

from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

# Define parameter grid

param_grid = {"n_estimators": [1000, 1200], "learning_rate": [0.1, 0.3], "max_depth": [4, 6, 8]}

# Create XGBoost model
xgb = XGBRegressor(random_state=7)

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    n_jobs=4,
    verbose=100,
)

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", -grid_search.best_score_)

# Best model
best_model = grid_search.best_estimator_
print("Best Model: ", best_model)

import joblib
from sklearn.metrics import r2_score
from xgboost import XGBRegressor

# Create and fit the model
model = XGBRegressor(
    n_estimators=1200, learning_rate=0.1, max_depth=4, min_child_weight=9, random_state=7
)
model.fit(X_train, y_train)

# Save the training model
joblib.dump(model, "models/XBR_trained_hdb_resale_model.pkl")

# Find the error rate on the test dataset
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: ", mae)

# Find the R2 on the test dataset
r2 = r2_score(y_test, model.predict(X_test))
print("R-squared Score: ", r2)

"""
Test Set Mean Absolute Error:  18286.493206061932
R-squared Score:  0.9770734652679451
"""

"""
params = {     'max_depth': 6,     'min_child_weight': 1,     'eta': 0.3,     'subsample': 1,     'colsample_bytree': 1 }
"""
